FORMAT: 1A
HOST: http://salsah.org

# salsah-api
SALSAH is a *Vritual Research Environment* allowing you to work with digital sources. The SALSAH-API is used by the
SALSAH GUI App to interact with the SALSAH-Core. It can be used by third-party developers for creating a two-way
bridge between SALSAH and their application, or for creating a completely new GUI.

# Group SALSAH Resources
In SALSAH we are always working on *SALSAH Resources* which are representations of some object, e.g., Book, Manuscript, Incunabula, etc.

##  Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204