FORMAT: 1A
HOST: http://salsah.org

# salsah-api
SALSAH is a *Vritual Research Environment* allowing you to work with digital sources. The SALSAH-API is used by the
SALSAH GUI App to interact with the SALSAH-Core. It can be used by third-party developers for creating a two-way
bridge between SALSAH and their application, or for creating a completely new GUI.

# Group SALSAH Resources
In SALSAH we are always working on *SALSAH Resources* which are representations of some object, e.g., Book, Manuscript, Incunabula, etc.

##  Collection [/Resources]
### List all Resources [GET]
This request is 
+ Response 200 (application/json)

        {
        "status":0,
        "resources":
            [
                {"id":"1","value":["Zeitgl\u00f6cklein des Lebens und Leidens Christi"]},
                {"id":"2","value":["a1r, Titelblatt"]},
                {"id":"3","value":["a1v, Titelblatt, R\u00fcckseite"]}
            ],
        "userdata":{"lang":"en","extsearch":{"display_type":"table","saved_query":{"type":"SELECT","tables":["resource"],"fields":["resource.id","resource.person_id","resource.project_id"],"clauses":[[{"field":"resource.resource_type_id"},"=",{"integer":55}],"AND",[{"field":"resource.project_id"},"=",{"integer":13}]],"orderby":null,"groupby":null,"limits":null,"distinct":true,"calc_rows":false},"property_id":0,"start_at":0,"show_nrows":-1}}}
        }

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204